site_name: NZSSDT Documentation
site_url: https://gns-science.github.io/nzssdt-2023
repo_url: https://github.com/GNS-Science/nzssdt-2023
repo_name: GNS-Science/nzssdt-2023
strict: false
watch:
  - nzssdt_2023
  - docs
nav:
  - Home: index.md
  - Usage:
    - usage.md
    - Versions: versions.md
  - Process:
    - process.md
    - Scripts:
      - publish script: scripts/publish_cli.md
  - Development and Contributing:
    - contributing.md
    - Installation: installation.md
    - Testing: testing.md
    - API:
      - nzssdt: api/index.md
      - nzssdt.build: api/build.md
      - nzssdt.config: api/config.md
      - nzssdt.versioning: api/versioning.md
      - nzssdt.data_creation: api/data_creation.md
      - nzssdt.convert: api/convert.md
      - nzssdt.publish: api/publish.md
  - Changelog: changelog.md
theme:
  name: material
  language: en
  #logo: assets/logo.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    # - navigation.tabs.sticky

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - mkdocs-click
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
  - tables

plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_if_no_docstring: true
            signature_crossrefs: true
            annotations_path: source
            # show_source: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GNS-Science/solvis
      name: GitHub
    - icon: material/email
      link: "mailto:nshm@gns.cri.nz"