[project]
name = "nzssdt-2023"
version = "0.8.0"
description = "Data resource library for the NZ Seismic Site Demand Table 2023"
license = "AGPL-3.0-or-later"
readme = "README.md"
authors = [
    { name = "Chris B Chamberlain", email = "chrisbc@artisan.co.nz" },
    {name = "Chris DiCaprio", email = "christopher.dicaprio@gmail.com"},
    {name="Anne Hulsey"},
    {name="NSHM Compute Working Group", email="nshm@gns.cri.nz"}
]

classifiers=[
    'Development Status :: 2 - Pre-Alpha',
    'Intended Audience :: Developers',
    'Natural Language :: English',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
]
requires-python = ">=3.10,<3.13"

dependencies = [
    "pandas>=2.0.2",
    "click>=8.1.3",
    "dacite>=1.8.1",
    "borb>=2.1.13,<3.0",
    "h5py>=3.11.0",
    "geopandas>=1.0.1",
    "openpyxl>=3.1.5",
    "nzshm-common>=0.8.4",
    "shapely>=2.0.7",
    "toshi-hazard-store==1.0.0",
]

[project.scripts]
pipeline = "nzssdt_2023.scripts.pipeline_cli:cli"

[dependency-groups]
dev = [
    "bump2version",
    "mypy",
    "pip-audit>=2.9.0,<3.0.0",
    "pre-commit",
    "pytest-cov",
    "pytest",
    "ruff",
    "safety>=3.6.2,<4.0.0",
    "shapely",
    "toml",
    "tox",
    "twine",
    "pytest-lazy-fixtures",
    "pytest-mock"
]

doc = [
    "griffe>=1.14.0,<3.0.0",
    "mkdocs-autorefs",
    "mkdocs-click>=0.9.0,<0.10.0",
    "mkdocs-include-markdown-plugin",
    "mkdocs-material-extensions",
    "mkdocs-material",
    "mkdocs",
    "mkdocstrings-python>=1.18.2,<3.0.0",
    "mkdocstrings",
    "mkdocs-with-pdf"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["nzssdt_2023"]

[tool.uv]
exclude-newer = "1 week"
exclude-newer-package = { "nzshm-common" = false }

[tool.mypy]
ignore_missing_imports = true
exclude = "nzssdt_2023/scripts"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.format]
quote-style = "preserve"
