[tool.poetry]
name = "srwg-sat"
version = "0.1.0"
description = "python resource library for NZ SaT"
authors = ["NSHM project <nshm@gns.cri.nz>"]
license = "AGPL3"
readme = "README.md"
packages = [{include = "srwg_sat"}]

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.0.2"

[tool.poetry.group.dev.dependencies]
black  = { version = "^22.3"}
bump2version = {version = "^1.0.1"}
flake8  = { version = "^3.9.2"}
flake8-docstrings = { version = "^1.6.0", optional = true }
isort  = { version = "^5.8.0"}
mypy = {version = "^0.900"}
pre-commit = {version = "^2.12.0", optional = true}
pytest = { version = "^6.2.4"}
pytest-cov  = { version = "^2.12.0"}
tox = "^4.5.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
